steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-docker-file'
    args: ['build', '-t', 'asia-northeast3-docker.pkg.dev/majestic-trail-408701/gcp-demo/gcp-demo', '-f', './Dockerfile', '.']

  - name : 'gcr.io/cloud-builders/docker'
    id: 'push-docker-file-artifact-registry'
    args: ['push', 'asia-northeast3-docker.pkg.dev/majestic-trail-408701/gcp-demo/gcp-demo']

  - name : 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'gcp', '--image', 'asia-northeast3-docker.pkg.dev/majestic-trail-408701/gcp-demo/gcp-demo', '--region', 'asia-northeast3']

